//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForBeautyMaui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForBeautyMaui.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To ShoppingCart.
        /// </summary>
        internal static string AddToShoppingCart {
            get {
                return ResourceManager.GetString("AddToShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Area *.
        /// </summary>
        internal static string AreaDelivery {
            get {
                return ResourceManager.GetString("AreaDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best brands.
        /// </summary>
        internal static string BestBrands {
            get {
                return ResourceManager.GetString("BestBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best categories.
        /// </summary>
        internal static string BestCategories {
            get {
                return ResourceManager.GetString("BestCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite searches.
        /// </summary>
        internal static string BestSearch {
            get {
                return ResourceManager.GetString("BestSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string BtnDiscountCode {
            get {
                return ResourceManager.GetString("BtnDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the area.
        /// </summary>
        internal static string ChoseAreaDelivery {
            get {
                return ResourceManager.GetString("ChoseAreaDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the city.
        /// </summary>
        internal static string ChoseCityDelivery {
            get {
                return ResourceManager.GetString("ChoseCityDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    City *.
        /// </summary>
        internal static string CityDelivery {
            get {
                return ResourceManager.GetString("CityDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.l.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery options.
        /// </summary>
        internal static string DelliveryOptions {
            get {
                return ResourceManager.GetString("DelliveryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dicount code ?.
        /// </summary>
        internal static string DicountCode {
            get {
                return ResourceManager.GetString("DicountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter discount code.
        /// </summary>
        internal static string DicountCodeEnty {
            get {
                return ResourceManager.GetString("DicountCodeEnty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in or create an account to enjoy.
        /// </summary>
        internal static string DoLoginOrRegisterAcouunt {
            get {
                return ResourceManager.GetString("DoLoginOrRegisterAcouunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all the benefits of ForBeauty.
        /// </summary>
        internal static string DoLoginOrRegisterAcouunt2 {
            get {
                return ResourceManager.GetString("DoLoginOrRegisterAcouunt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wish list is still empty.
        /// </summary>
        internal static string FavouriteEmpty {
            get {
                return ResourceManager.GetString("FavouriteEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any items on your wish list yet.Browse through.
        /// </summary>
        internal static string FavouriteEmpty1 {
            get {
                return ResourceManager.GetString("FavouriteEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our top categories to find the best product.
        /// </summary>
        internal static string FavouriteEmpty2 {
            get {
                return ResourceManager.GetString("FavouriteEmpty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free shopping from 200 dl.
        /// </summary>
        internal static string FreeShopping {
            get {
                return ResourceManager.GetString("FreeShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least 1 surprise for.
        /// </summary>
        internal static string Gift1 {
            get {
                return ResourceManager.GetString("Gift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an order from 200 dl.
        /// </summary>
        internal static string Gift2 {
            get {
                return ResourceManager.GetString("Gift2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts&amp;Boxs.
        /// </summary>
        internal static string GiftsBoxs {
            get {
                return ResourceManager.GetString("GiftsBoxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/FAQ.
        /// </summary>
        internal static string HelpQ {
            get {
                return ResourceManager.GetString("HelpQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a friend.
        /// </summary>
        internal static string InviteFriend {
            get {
                return ResourceManager.GetString("InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string LblDiscount {
            get {
                return ResourceManager.GetString("LblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string LblTotalPrice {
            get {
                return ResourceManager.GetString("LblTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New In.
        /// </summary>
        internal static string NewIn {
            get {
                return ResourceManager.GetString("NewIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no previous orders.
        /// </summary>
        internal static string NoPrevuseOrder {
            get {
                return ResourceManager.GetString("NoPrevuseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order id.
        /// </summary>
        internal static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment options.
        /// </summary>
        internal static string PaymentOptions {
            get {
                return ResourceManager.GetString("PaymentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal informations.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUp.
        /// </summary>
        internal static string PickUp {
            get {
                return ResourceManager.GetString("PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous orders.
        /// </summary>
        internal static string PreviousOrders {
            get {
                return ResourceManager.GetString("PreviousOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback on the app.
        /// </summary>
        internal static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently viewed.
        /// </summary>
        internal static string RecentlyViewed {
            get {
                return ResourceManager.GetString("RecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return only.
        /// </summary>
        internal static string Return1 {
            get {
                return ResourceManager.GetString("Return1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the same day.
        /// </summary>
        internal static string Return2 {
            get {
                return ResourceManager.GetString("Return2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search for your favourite product 🔍 .
        /// </summary>
        internal static string SearchEntry {
            get {
                return ResourceManager.GetString("SearchEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shopping cart is empty.
        /// </summary>
        internal static string ShoppingCartEmpty {
            get {
                return ResourceManager.GetString("ShoppingCartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To checkout.
        /// </summary>
        internal static string ToCheckOut {
            get {
                return ResourceManager.GetString("ToCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Trem&amp;condictions ForBeauty.
        /// </summary>
        internal static string TremCondictions {
            get {
                return ResourceManager.GetString("TremCondictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish list.
        /// </summary>
        internal static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may also like.
        /// </summary>
        internal static string YouMayAlsoLike {
            get {
                return ResourceManager.GetString("YouMayAlsoLike", resourceCulture);
            }
        }
    }
}
